# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'DemoMovie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers! 

  # Pods for DemoMovie
  pod 'Alamofire', '~> 4.0'

  target 'DemoMovieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoMovieUITests' do
    # Pods for testing
  end

end
